manager:
  name: feedback_manager
  version: "1.0.0"

children:
  style_selector: "./style_selector"
  gemini_generator: "./gemini_generator"

rate_limiting:
  delay_between_calls_seconds: 60

logging:
  level: INFO
  file: "./logs/feedback_manager.log"
  console: true
  format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
